// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW7mjcTT8IE2rsVOOR0pwS4y8cbnZNekE',
    appId: '1:20665449462:web:c95ee95b19a539ef97a5d7',
    messagingSenderId: '20665449462',
    projectId: 'appdev-649c7',
    authDomain: 'appdev-649c7.firebaseapp.com',
    storageBucket: 'appdev-649c7.appspot.com',
    measurementId: 'G-RDZW78XRRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdisFCvfcQVsX6lOPkiphjRRIrcI59lB4',
    appId: '1:20665449462:android:3e3ef500aaff592397a5d7',
    messagingSenderId: '20665449462',
    projectId: 'appdev-649c7',
    storageBucket: 'appdev-649c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGkOzIR2dsyimRRdc4aTY0enmolNDz5kk',
    appId: '1:20665449462:ios:ba61d2d1d1705a8297a5d7',
    messagingSenderId: '20665449462',
    projectId: 'appdev-649c7',
    storageBucket: 'appdev-649c7.appspot.com',
    iosBundleId: 'com.example.fiv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGkOzIR2dsyimRRdc4aTY0enmolNDz5kk',
    appId: '1:20665449462:ios:ba61d2d1d1705a8297a5d7',
    messagingSenderId: '20665449462',
    projectId: 'appdev-649c7',
    storageBucket: 'appdev-649c7.appspot.com',
    iosBundleId: 'com.example.fiv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW7mjcTT8IE2rsVOOR0pwS4y8cbnZNekE',
    appId: '1:20665449462:web:5c80ffe85fe0db2a97a5d7',
    messagingSenderId: '20665449462',
    projectId: 'appdev-649c7',
    authDomain: 'appdev-649c7.firebaseapp.com',
    storageBucket: 'appdev-649c7.appspot.com',
    measurementId: 'G-C7BBK61QFS',
  );
}
